### PR TITLE
Proper timestamp calculation for UUID v7

### LINKED ISSUE #195: TimestampFromUUIDv7 Artificially Limited
### Welcome

- [x] Yes, I'm using the latest release.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.

### What did you expect to see?

The maximum UUIDv7 should have a timestamp that evaluates to the year 10889 per https://www.rfc-editor.org/rfc/rfc9562.html#section-6.1-2.8

> Length:
>     The length of a given timestamp directly impacts how many timestamp ticks can be contained in a UUID before the maximum value for the timestamp field is reached. Take care to ensure that the proper length is selected for a given timestamp. UUIDv1 and UUIDv6 utilize a 60-bit timestamp valid until 5623 AD; UUIDv7 features a 48-bit timestamp valid until the year 10889 AD.

### What did you see instead?

The maximum UUIDv7 had a timestamp that evaluated to the year 2121. 

```
go test -v -timeout 30s -run ^TestTimestampFromV7$ github.com/gofrs/uuid/v5 -race -count=1 -v

=== RUN   TestTimestampFromV7
    uuid_test.go:275: 1969-12-31 18:00:00 -0600 CST <nil>
    uuid_test.go:275: 2023-09-13 14:02:18.605 -0500 CDT <nil>
    uuid_test.go:275: 2121-04-11 06:53:25.0117257 -0500 CDT <nil>
--- PASS: TestTimestampFromV7 (0.00s)
PASS
ok  	github.com/gofrs/uuid/v5	1.194s
```

This is likely because of inappropriate function re-use between v1 and v7 and an overflow somewhere (though I haven't fully debugged to prove that):

uuid.go:84-67
```
// Timestamp is the count of 100-nanosecond intervals since 00:00:00.00,
// 15 October 1582 within a V1 UUID. This type has no meaning for other
// UUID versions since they don't have an embedded timestamp.
type Timestamp uint64

const _100nsPerSecond = 10000000

// Time returns the UTC time.Time representation of a Timestamp
func (t Timestamp) Time() (time.Time, error) {
	secs := uint64(t) / _100nsPerSecond
	nsecs := 100 * (uint64(t) % _100nsPerSecond)

	return time.Unix(int64(secs)-(epochStart/_100nsPerSecond), int64(nsecs)), nil
}
```

### Reproduction steps

```console
Simple patch to the existing test file to see the values embedded in already-present tests:


diff --git a/uuid_test.go b/uuid_test.go
index 6dc97f9..7837c45 100644
--- a/uuid_test.go
+++ b/uuid_test.go
@@ -271,6 +271,10 @@ func TestTimestampFromV7(t *testing.T) {
        for _, tt := range tests {
                got, err := TimestampFromV7(tt.u)
 
+               if err == nil {
+                       t.Log(got.Time())
+               }
+
                switch {
                case tt.wanterr && err == nil:
                        t.Errorf("TimestampFromV7(%v) want error, got %v", tt.u, got)




go test -v -timeout 30s -run ^TestTimestampFromV7$ github.com/gofrs/uuid/v5 -race -count=1 -v

=== RUN   TestTimestampFromV7
    uuid_test.go:275: 1969-12-31 18:00:00 -0600 CST <nil>
    uuid_test.go:275: 2023-09-13 14:02:18.605 -0500 CDT <nil>
    uuid_test.go:275: 2121-04-11 06:53:25.0117257 -0500 CDT <nil>
--- PASS: TestTimestampFromV7 (0.00s)
PASS
ok  	github.com/gofrs/uuid/v5	1.194s
```

### Version of flock

N/A

### Logs

```console
N/A
```

### Go environment

go version go1.23.3 darwin/arm64

### Validation

- [x] Yes, I've included all information above (version, config, etc.).

### PR DESCRIPTION
**Pull request by kohenkatz**
Fixes #195.

The use of the `time.Time` method `UnixNanos()` was causing an `int64` overflow (officially an "undefined behavior"), and returning incorrect timestamp values.

There wasn't any good reason for using this function, since the goal is to convert milliseconds to 100-nanosecond intervals, which can be done much more simply with a single multiplication step.

---

This might also provide a slight performance improvement (see https://github.com/gofrs/uuid/issues/128#issuecomment-2106517809), since `time.UnixMilli`, the (unneeded) call to `.UTC()`, and `.UnixNano()` are each doing a fair bit of work internally, and they have all been replaced with a single multiplication.

### CODE REVIEW

File: uuid_test.go [hunk 1]
```diff
@@ -262,11 +262,11 @@ func TestTimestampFromV7(t *testing.T) {
 		want    Timestamp
 		wanterr bool
 	}{
-		{u: Must(NewV1()), wanterr: true},
```
Comment (nathanmcgarvey-modopayments) [inline uuid_test.go:265]: Did you mean to remove this test case that throws an error?

**Review by nathanmcgarvey-modopayments — COMMENTED** [review]
Would you potentially accept a couple of benchmarks if I wrote them?

File: uuid_test.go (hunk 1 above)
Comment (kohenkatz) [reply uuid_test.go:265]: That test case relevant here. It was a copy paste mistake from the v1 tests. In V7, it doesn't return an error.

**Comment by kohenkatz** [comment]
> Would you potentially accept a couple of benchmarks if I wrote them?

Sure!

**Comment by nathanmcgarvey-modopayments** [comment]
> > Would you potentially accept a couple of benchmarks if I wrote them?
> 
> Sure!

https://github.com/kohenkatz/uuid/pull/1

File: uuid_test.go (hunk 1 above)
Comment (nathanmcgarvey-modopayments) [reply uuid_test.go:265]: That's surprising since it is in the v1 and v6 tests and there is an actual case statment to handle it:

```golang
		switch {
		case tt.wanterr && err == nil:
			t.Errorf("TimestampFromV7(%v) want error, got %v", tt.u, got)
```

Surely it should be an error if you try to do a TimestampFromV7 with a NewV1 UUID.

Comment (kohenkatz) [reply uuid_test.go:265]: @nathanmcgarvey-modopayments You are right, I was misreading it. I am putting it back with a note explaining why it's there.

**Review by nathanmcgarvey-modopayments — APPROVED** [review]

File: generator_test.go [hunk 2]
```diff
@@ -1101,6 +1101,7 @@ func TestDefaultHWAddrFunc(t *testing.T) {
 }
 
 func BenchmarkGenerator(b *testing.B) {
+	b.ReportAllocs()
```
Comment (dylan-bourque) [inline generator_test.go:1104]: Personal opinion: it's cleaner to not have this directly in the benchmark and include `-benchmem` when running `go test`.  This way you **can't** only benchmark times without modifying the code.

File: uuid.go [hunk 3]
```diff
@@ -141,7 +144,7 @@ func TimestampFromV7(u UUID) (Timestamp, error) {
 		int64(u[5])
 
 	// convert to format expected by Timestamp
-	tsNanos := epochStart + time.UnixMilli(t).UTC().UnixNano()/100
+	tsNanos := epochStart + (t * _100nsPerMillisecond)
```
Comment (dylan-bourque) [inline uuid.go:147]: I'd like to see an explanatory comment here since now it's "magic math".

File: uuid_test.go [hunk 4]
```diff
@@ -281,6 +284,56 @@ func TestTimestampFromV7(t *testing.T) {
 	}
 }
 
+func TestTimestampMinMaxV167(t *testing.T) {
```
Comment (dylan-bourque) [inline uuid_test.go:287]:
```suggestion
func TestMinMaxTimestamps(t *testing.T) {
```
Timestamps are only valid for V1, V6 and V7 values and mashing the 3 version together makes for a clunky name IMO.

File: uuid_test.go [hunk 5]
```diff
@@ -300,3 +353,94 @@ func BenchmarkFormat(b *testing.B) {
 		})
 	}
 }
+
+var uuidBenchmarkSink UUID
+var timestampBenchmarkSink Timestamp
+var timeBenchmarkSink time.Time
+
+func BenchmarkTimestampFrom(b *testing.B) {
+	b.ReportAllocs()
```
Comment (dylan-bourque) [inline uuid_test.go:362]: Same note here re: forcing memory benchmarking

File: uuid_test.go [hunk 6]
```diff
@@ -300,3 +353,94 @@ func BenchmarkFormat(b *testing.B) {
...
+				if err != nil {
+					b.Fatal(err)
+				}
+			}
+		})
+	}
+}
+
+func BenchmarkTimestampTime(b *testing.B) {
+	b.ReportAllocs()
```
Comment (dylan-bourque) [inline uuid_test.go:403]: And here

**Comment by kohenkatz** [comment]
@dylan-bourque Updated with your suggestions.

File: uuid.go [hunk 7]
```diff
@@ -144,8 +147,11 @@ func TimestampFromV7(u UUID) (Timestamp, error) {
 		(int64(u[4]) << 8) |
 		int64(u[5])
 
-	// convert to format expected by Timestamp
-	tsNanos := epochStart + time.UnixMilli(t).UTC().UnixNano()/100
+	// UUIDv7 stores MS since 1979-01-01 00:00:00, but the Timestamp
+	// type stores 100-nanosecond increments since 1582-10-15 00:00:00.
+	// This conversion multiplies ms by 10,000 to get 100-ns chunks and adds
+	// the difference between October 1582 and January 1979.
```
Comment (nathanmcgarvey-modopayments) [inline uuid.go:153]: s/1979/1970

**Review by nathanmcgarvey-modopayments — CHANGES_REQUESTED** [review]

File: uuid.go (hunk 7 above)
Comment (nathanmcgarvey-modopayments) [reply uuid.go:153]: (two occurrences)

Comment (kohenkatz) [reply uuid.go:153]: Fixed. Must have been sitting a little to far to the left relative to my keyboard... 😅

**Review by nathanmcgarvey-modopayments — APPROVED** [review]

File: uuid.go [hunk 8]
```diff
@@ -82,11 +82,14 @@ const (
...
-// 15 October 1582 within a V1 UUID. This type has no meaning for other
-// UUID versions since they don't have an embedded timestamp.
+// 15 October 1582 within a V1 or V6 UUID, or as a common intermediate
+// representation of the (Unix Millisecond) timestamp within a V7 UUID.
+// This type has no meaning for other UUID versions since they don't
+// have an embedded timestamp.
 type Timestamp uint64
 
 const _100nsPerSecond = 10000000
+const _100nsPerMillisecond = 10000
```
Comment (dylan-bourque) [inline uuid.go:92]: One more nit: not really a fan of defining a named constant that's only used in a single place as an implementation detail.  it breaks code locality.

Comment (kohenkatz) [reply uuid.go:92]: I thought about that, but I'd rather have both time conversion constants next to each other so future devs can see the relationship between them.

Comment (dylan-bourque) [reply uuid.go:92]: counter-point: the name `_100nsPerMillisecond` doesn't convey what the value represents (there aren't 100 ns in a millisecond 🤨) or how it's used.  a casual reader would see this and have to grep the code to figure out why this constant exists.

fwiw I have the same gripe with `_100nsPerSecond` but that one precedes my being a maintainer.

Comment (kohenkatz) [reply uuid.go]: I it's not worth spending more time discussing this. Since there's already a comment that explains the conversion, I changed it to just use a "magic number" there instead of a constant.

Comment (dylan-bourque) [reply uuid.go]: > I understand the names to perfectly convey what the value represents 

in a way this reinforces my gripe.  we both read the same code and interpreted the name differently. 😉

**Review by dylan-bourque — APPROVED** [review]
